import AVFoundation

/// Holds decoded one-shot audio buffers for a single drum machine's instruments, keyed by
/// instrument code. Built once for the active machine (the TR-808 in the MVP) and reused by
/// the sequencer so every hit triggers from memory (no disk reads on the audio path).
public final class SampleBank: SampleSource {

    public let machine: DrumMachine
    private let buffers: [String: AVAudioPCMBuffer]

    /// The audio format of the loaded samples (all 808 one-shots share one format).
    /// The sequencer connects its player nodes using this format.
    public let commonFormat: AVAudioFormat

    /// Decode every instrument sample for `machine` from `bundle` (defaults to the package's
    /// bundled resources). Instruments whose file can't be read are skipped rather than
    /// failing the whole bank.
    public init(machine: DrumMachine, bundle: Bundle? = nil) throws {
        // `Bundle.module` is internal (generated by SPM), so it can't be a public default
        // argument; resolve it inside the body instead. Passing nil uses the package bundle.
        let bundle = bundle ?? Bundle.module
        self.machine = machine

        var loaded: [String: AVAudioPCMBuffer] = [:]
        var format: AVAudioFormat?
        for instrument in machine.instruments {
            // filenames include their extension (e.g. "Roland_Tr-808_full__36kick.mp3"); split
            // so Bundle can locate them under the "audio" resource subdirectory.
            let nsName = instrument.filename as NSString
            guard let url = bundle.url(forResource: nsName.deletingPathExtension,
                                       withExtension: nsName.pathExtension,
                                       subdirectory: "audio") else { continue }
            guard let file = try? AVAudioFile(forReading: url) else { continue }

            let fileFormat = file.processingFormat
            guard let buffer = AVAudioPCMBuffer(pcmFormat: fileFormat,
                                                frameCapacity: AVAudioFrameCount(file.length)) else { continue }
            do {
                try file.read(into: buffer)
            } catch {
                continue
            }
            loaded[instrument.code] = buffer
            if format == nil { format = fileFormat }
        }

        guard let commonFormat = format else {
            throw SampleBankError.noSamplesLoaded
        }
        self.buffers = loaded
        self.commonFormat = commonFormat
    }

    /// The decoded buffer for an instrument code, or nil if the machine lacks it / it failed
    /// to load.
    public func buffer(for code: String) -> AVAudioPCMBuffer? { buffers[code] }

    /// All instrument codes that successfully loaded.
    public var loadedCodes: [String] { Array(buffers.keys) }
}

public enum SampleBankError: Error {
    case noSamplesLoaded
}
